
Trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 5
  val_check_interval: 2000
  accumulate_grad_batches: 2
  gradient_clip_val: 1.0
  log_every_n_steps: 50


Callbacks:
  LearningRateMonitor:
    logging_interval: step

  EarlyStopping:
    monitor: val_rouge2
    patience: 10
    mode: max

  ModelCheckpoint:
    monitor: val_rouge2
    save_top_k: 5
    mode: max
    dirpath: checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}


Profiler:
  SimpleProfiler:
